[project]
authors = ["Connor Robertson <cjrobe@sandia.gov>"]
channels = ["conda-forge"]
description = "Environment for calibration CityCOVID agent-based model"
name = "citycovid_calibration"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
PROJLOC = "$PIXI_PROJECT_ROOT"

[dependencies]
python = "3.12.*"
numpy = "*"
scikit-learn = "*"
matplotlib = "*"
pandas = "*"
properscoring = "*"
r-base = ">=4.4.1,<4.5"
r-mcgibbsit = ">=1.2.2,<2"

[pypi-dependencies]
pymcmcstat = { git = "https://github.com/cnrrobertson/pymcmcstat" }
mcmcplot = {git = "https://github.com/cnrrobertson/mcmcplot"}

[feature.dev.dependencies]
ipython = ">=8.31.0,<9"
r-irkernel = ">=1.3.2,<2"
jupyter_console = ">=6.6.3,<7"
pynvim = "*"

[environments]
dev = ["dev"]
